---
- name: Deploy Node.js Environment App
  hosts: remote
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
    app_dir: "/home/dev/app"
    repo_url: "https://github.com/Usama306/FYP-DevOps.git"
    node_version: "18"
    packages:
      - git
      - curl
      - python3
      - python3-pip

  tasks:
    - name: Wait for apt lock to be released
      shell: while lsof /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 5; done;
      changed_when: false

    - name: Kill any existing apt processes
      shell: |
        killall apt apt-get || true
        rm -f /var/lib/dpkg/lock-frontend
        rm -f /var/lib/dpkg/lock
        dpkg --configure -a
      ignore_errors: yes

    - name: Remove old Node.js
      apt:
        name: nodejs
        state: absent
      ignore_errors: yes

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      register: apt_update_result
      retries: 5
      delay: 10
      until: apt_update_result is success

    - name: Install required packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: no
      register: apt_install_result
      retries: 5
      delay: 10
      until: apt_install_result is success

    - name: Download Node.js setup script
      get_url:
        url: "https://deb.nodesource.com/setup_{{ node_version }}.x"
        dest: /tmp/nodesource_setup.sh
        mode: '0755'

    - name: Run Node.js setup script
      command: /tmp/nodesource_setup.sh
      register: node_setup
      changed_when: node_setup.rc == 0

    - name: Install Node.js
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      register: docker_key_result
      retries: 3
      delay: 5
      until: docker_key_result is success

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
      register: docker_repo_result
      retries: 3
      delay: 5
      until: docker_repo_result is success

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      register: docker_install_result
      retries: 3
      delay: 5
      until: docker_install_result is success

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'
      register: compose_install_result
      retries: 3
      delay: 5
      until: compose_install_result is success

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Create app directory if it doesn't exist
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Pull latest code from GitHub
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        update: yes
        force: yes

    - name: Set directory permissions
      file:
        path: "{{ app_dir }}"
        state: directory
        recurse: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Create public directory
      file:
        path: "{{ app_dir }}/app/public"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Display Node.js and npm versions
      shell: |
        node --version
        npm --version
      register: versions

    - name: Show versions
      debug:
        var: versions.stdout_lines

    - name: Clean npm cache
      command: npm cache clean --force
      args:
        chdir: "{{ app_dir }}/app"
      become: yes
      become_user: "{{ ansible_user }}"

    - name: Remove node_modules
      file:
        path: "{{ app_dir }}/app/node_modules"
        state: absent

    - name: Install Node.js dependencies
      npm:
        path: "{{ app_dir }}/app"
        state: present
      become: yes
      become_user: "{{ ansible_user }}"

    - name: Install Tailwind CSS globally
      npm:
        name: tailwindcss
        global: yes
        state: present
      become: yes

    - name: Build the CSS
      shell: |
        cd {{ app_dir }}/app
        npx tailwindcss -i ./src/styles/main.css -o ./public/styles.css --minify
      become: yes
      become_user: "{{ ansible_user }}"

    - name: Stop existing Docker containers
      command: docker compose down
      args:
        chdir: "{{ app_dir }}"
      ignore_errors: yes
      become: yes
      become_user: "{{ ansible_user }}"

    - name: Build and start Docker containers
      command: docker compose up -d --build
      args:
        chdir: "{{ app_dir }}"
      become: yes
      become_user: "{{ ansible_user }}"

    - name: Wait for containers to be running
      wait_for:
        timeout: 30

    - name: Check container status
      command: docker ps
      register: container_status
      become: yes
      become_user: "{{ ansible_user }}"

    - name: Display container status
      debug:
        var: container_status.stdout_lines

    - name: Verify application endpoints
      uri:
        url: "http://localhost:{{ item.port }}"
        return_content: yes
        status_code: 200
      loop:
        - { port: 3001, env: "Development" }
        - { port: 3002, env: "Test" }
        - { port: 3003, env: "Production" }
      register: endpoint_check
      ignore_errors: yes